EXTERN_C_START

NTSTATUS KSGLDRVQueueInitialize(_In_ WDFDEVICE Device);

EVT_WDF_IO_QUEUE_IO_DEVICE_CONTROL KSGLDRVEvtIoDeviceControl;
EVT_WDF_IO_QUEUE_IO_STOP           KSGLDRVEvtIoStop;
EVT_WDF_FILE_CLEANUP               KSGLDRVEvtDeviceFileCleanup;

EXTERN_C_END
